import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import {
  Container,
  Center,
  AppShell,
  Navbar,
  Header,
  Button,
  Group
} from "@mantine/core";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell className={}
        padding="md"
        header={
          <Header height={60} p="xs">
            <Group position="center">
              <Link href="/"><Button variant="subtle">Home</Button></Link>
              <Link href="/projects"><Button variant="subtle">Projects</Button></Link>
              <Link href="/resume"><Button variant="subtle">Resume</Button></Link>
              <Link href="/contact"><Button variant="subtle">Contact</Button></Link>

            </Group>

          </Header>}
      >
        <Container size="fluid" className='content'><Center><h1>Hi, I'm Nurul!</h1></Center></Container>

      </AppShell>
    </>
  )
}
